### ISSUE TITLE
CoffeeHouse 2.0 compatibility

### ISSUE THREAD

**Issue by Netkas** [intellivoid/CoffeeHouse-Python-API-Wrapper#11]
The upcoming CoffeeHouse 2.0 will introduce new features, but also changes. There is time to update all existing API Wrappers to use these new features but it's important to make sure it's also backwards compatible at the time of it's release.

The current API methods will have minor changes in it's results, for example; the current response from a Create Session method will return something like this

```json
{
  "success": true,
  "response_code": 200,
  "payload": {
    "session_id": "46db504f80a9eadd0fbec43ff4f75690962242b5c57fb23f6e4f2a23423bcab8",
    "language": "en",
    "available": true,
    "expires": 1581899765
  }
}
```

However, the upcoming update will replace `payload` with `results` in every JSON response, so for example the new update will return a response like this

```json
{
  "success": true,
  "response_code": 200,
  "results": {
    "session_id": "46db504f80a9eadd0fbec43ff4f75690962242b5c57fb23f6e4f2a23423bcab8",
    "language": "en",
    "available": true,
    "expires": 1581899765
  }
}
```

The goal is to make an update to make sure that the current API wrapper will still be compatible after the API update and before the API update, a simple `if` logic can be used to check if the results are either `payload` or `results`.

This will not be permanent and the check can be removed after the update has been released, this is designed for users who can't get around to immediately updating the API wrapper around the time CoffeeHouse 2.0 gets released and will buy them some time to do so, but in the meantime they can use this update to be prepared for the change.

**Comment by nocturn9x** [comment]
Check commit `ef6eb82415421ab2a3d00c1e3c744abe0f537fb3` for the updated version
